#!/bin/bash
RED='\033[0;31m'
NC='\033[0m'

case $1 in
  up) docker compose up;;
  stop) docker compose stop;;
  build) docker compose build;;
  bash)	docker compose run --rm backend bash;;
  console | c) docker compose run --rm backend irb -r ./initializer.rb;;
  "") echo -e "${RED}Command wasn't passed${NC}" && exit 1;;
  *) echo -e "${RED}There is no command {$1}${NC}" && exit 1;;
esac
