version: '3.8'
services:
  backend:
    build:
      context: .
    network_mode: host
    command: puma
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres
  schedule:
    build:
      context: .
    network_mode: host
    command: ruby config/schedule.rb
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres
  redis:
    image: redis:5.0.7
    network_mode: host
    volumes:
      - redis:/data
  postgres:
    image: postgres:15-alpine
    network_mode: host
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  redis:
  postgres:
